#ifndef WINDOW_SIZE_H_INCLUDED
#define WINDOW_SIZE_H_INCLUDED

extern const int ORIGINAL_WINDOWS_WIDTH;
extern const int ORIGINAL_WINDOWS_HEIGHT;

extern int WINDOWS_WIDTH;
extern int WINDOWS_HEIGHT;

#endif //WINDOW_SIZE_H_INCLUDED
